# Generated by Django 2.2.1 on 2019-05-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='female_compl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('actv', models.FloatField()),
                ('css', models.IntegerField()),
                ('lp', models.IntegerField()),
                ('mgp', models.FloatField()),
                ('zs', models.IntegerField()),
                ('fv', models.IntegerField()),
                ('ibs', models.IntegerField()),
                ('csn', models.IntegerField()),
                ('chr_pan', models.IntegerField()),
                ('dad', models.IntegerField()),
                ('emot_coeff', models.FloatField()),
                ('comp_mor', models.IntegerField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='female_lethal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('glycose', models.FloatField()),
                ('erythrocyte', models.FloatField()),
                ('actv', models.FloatField()),
                ('css', models.IntegerField()),
                ('mfa', models.IntegerField()),
                ('takrolimus', models.IntegerField()),
                ('methylprednise', models.IntegerField()),
                ('dad', models.IntegerField()),
                ('kokraf', models.FloatField()),
                ('mdrd', models.FloatField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='male_compl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('lpvp', models.FloatField()),
                ('sd', models.IntegerField()),
                ('chr_pan', models.IntegerField()),
                ('psycho', models.IntegerField()),
                ('activity', models.IntegerField()),
                ('pg', models.IntegerField()),
                ('dad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='male_lethal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('prot_time', models.FloatField()),
                ('mgm', models.FloatField()),
                ('meld', models.FloatField()),
                ('vrvp', models.IntegerField()),
                ('bkk', models.IntegerField()),
                ('mfa', models.IntegerField()),
                ('sad', models.FloatField()),
                ('dad', models.FloatField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
    ]
