# Generated by Django 2.2.1 on 2019-05-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liver', '0002_auto_20190514_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='female_compl',
            name='zs',
            field=models.FloatField(),
        ),
    ]
