# Generated by Django 2.2.1 on 2019-05-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liver', '0004_point_network_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='z',
            field=models.FloatField(),
        ),
    ]
