# Generated by Django 2.2.1 on 2019-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liver', '0005_auto_20190527_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='z',
            new_name='acc_total',
        ),
        migrations.AddField(
            model_name='point',
            name='acc_test',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='acc_train',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
